###########################
# Builder Stage
###########################
FROM golang:1.24.9-alpine AS builder

ARG SERVICE

WORKDIR /activeOperations

COPY go.mod go.sum ./
RUN go env -w GOPROXY="https://goproxy.io,https://proxy.golang.org,https://goproxy.cn,direct"
RUN go mod download

COPY . .

# 编译指定微服务
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/mcp


###########################
# Runtime Stage
###########################
FROM alpine:latest

ARG SERVICE

WORKDIR /activeOperations

COPY --from=builder /activeOperations/app .
COPY --from=builder /activeOperations/k8s .

# 只有 agent 服务才需要文档与 bash 资源


EXPOSE 4321

CMD ["./app"]
