###########################
# Builder Stage
###########################
FROM golang:1.24.9-alpine AS builder

ARG SERVICE

WORKDIR /activeOperations

COPY go.mod go.sum ./
RUN go env -w GOPROXY="https://goproxy.io,https://proxy.golang.org,https://goproxy.cn,direct"
RUN go mod download

COPY . .

COPY ./docs /docs

# 编译指定微服务
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/agent


###########################
# Runtime Stage
###########################
FROM alpine:latest

ARG SERVICE

WORKDIR /activeOperations

COPY --from=builder /activeOperations/app .
COPY ./config.yaml ./config.yaml

COPY --from=builder docs /docs

EXPOSE 8080

CMD ["./app"]
